### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by Turatkg** [Eldar2021/my_quran#105]
- [ ] #106 
- [ ] #107
- [x] #108 
- [x] #111 
- [x] #82 
- [x] #113 
- [x] #114 
- [ ] Publish release

**Comment by Shabushii** [comment]
> - [ ] #106 
> 
> - [ ] #107
> 
> - [ ] #108 
> 
> - [ ] #111 
> 
> - [ ] Publish release

**Comment by Eldar2021** [comment]
#106 için UI kısmımız hazır durumda. Lütfen burayı kontrol edin #117

**Comment by Eldar2021** [comment]
I think done a bit :)
